### ISSUE TITLE
Provide data

### ISSUE THREAD

**Issue by LinguList** [lexibank/chechuroborrowing#1]
- etc/concepts.tsv
- etc/languages.tsv
- raw/sources.tsv
- raw/data.tsv

etc.

**Comment by LinguList** [comment]
@ilchec, can you look into this, and either directly upload or make a PR?

**Comment by ilchec** [comment]
Ready to upload the data but don't seem to have access, despite being a member of lexibank =( Can you please send me a new invite to this repo? Maybe the old one expired and I didn't accept it? No idea, what else may be the problem.

**Comment by tresoldi** [comment]
Just sent it, @ilchec , you only had read permission I think.

**Comment by ilchec** [comment]
Thanks! Done!

**Comment by LinguList** [comment]
Where's the data? The file words_IJB_submission.tsv lists data, but he data do not have any langauge identifiers that I can find in the file `etc/languages.tsv`.

**Comment by ilchec** [comment]
The words have to be mapped to metadata, then the language IDs will be accessible. I can do the mapping. Also I just realized that I need to change language names in languages.tsv to make a proper mapping because languages.tsv is overly detailed (I divided some entries because glottolog told me to, which was a bad idea).

**Comment by LinguList** [comment]
Please check my PR. And add the sources for the languages over there.
